/// Flutter icons Tinder_clone
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Tinder_clone
///      fonts:
///       - asset: fonts/Tinder_clone.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Tinder_clone {
  Tinder_clone._();

  static const _kFontFam = 'Tinder_clone';

  static const IconData iconfinder_338_tinder_logo_4375488__1_ = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData iconfinder_message_01_186393 = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData iconfinder_icons_user2_1564535 = IconData(0xe802, fontFamily: _kFontFam);
}
